//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FControl.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Cuenta
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Cuenta()
        {
            this.Transaccion = new HashSet<Transaccion>();
            this.Traspaso = new HashSet<Traspaso>();
            this.Traspaso1 = new HashSet<Traspaso>();
            this.Transaccion1 = new HashSet<Transaccion>();
        }
    
        public int CuentaID { get; set; }
        public Nullable<int> DivisaID { get; set; }
        public Nullable<double> SaldoInicial { get; set; }
        public string Concepto { get; set; }
        public Nullable<System.DateTime> FechaCuenta { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<int> TipoCuentaID { get; set; }
        public Nullable<int> EntidadEmisoraID { get; set; }
        public string Entidad { get; set; }
        public Nullable<int> NumeroTarjeta { get; set; }
        public Nullable<int> DiaCierre { get; set; }
        public Nullable<int> DiaPago { get; set; }
        public Nullable<double> LimiteCredito { get; set; }
        public string Nombre { get; set; }
        public Nullable<double> Total { get; set; }
        public Nullable<int> CompartidoID { get; set; }
    
        public virtual Divisa Divisa { get; set; }
        public virtual EntidadEmisora EntidadEmisora { get; set; }
        public virtual TipoCuenta TipoCuenta { get; set; }
        public virtual Usuario Usuario { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traspaso> Traspaso { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Traspaso> Traspaso1 { get; set; }
        public virtual Usuario Usuario1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Transaccion> Transaccion1 { get; set; }
    }
}
